### ISSUE TITLE
Provide bootstrap.min.css.gz unzipped

### ISSUE THREAD

**Issue by egze** [tompave/fun_with_flags_ui#10]
Similar topic was brought up here https://github.com/tompave/fun_with_flags_ui/issues/8

What we have is a load balancer overriding the accept-encoding headers and as a result - bootstrap.css is not loaded.

Would you accept a pull request where both versions of the file are available: gzipped and not?

**Comment by tompave** [comment]
Hi, thank you for reporting the issue.

I suppose that if you're posting here it's because you don't have access to the load balancer config, but it's still worth asking just to get it out of the way: have you tried to change the load balancer config to not override that header?

Also, what load balancer are you using, specifically? And I'd be curious to see what error the browser is getting. Is it a 404? Meaning that the Plug router won't opt to use the `gz` file because the modified request header says it's not acceptable?

As a workaround, you can try to intercept the requests for `/feature-flags/assets/bootstrap.min.css`  [1] before they enter the `fun_with_flags_ui` router.

There, in fact, they're handled with this [`Plug.Static`](https://hexdocs.pm/plug/1.8.0/Plug.Static.html#content) configuration:

https://github.com/tompave/fun_with_flags_ui/blob/v0.7.1/lib/fun_with_flags/ui/router.ex#L18-L21

You could try to declare that path in your application's router (either Phoenix or vanilla Plug) and direct it to a non-gzipped version of the file from your application's assets.

> Would you accept a pull request where both versions of the file are available: gzipped and not?

Yes, but I'd rather consider that a last resort to be honest. If you can't get it to work with the workaround above, you can just extract the gizipped file and commit it as it is. Since it's minified I suppose that vendoring it wouldn't be too bad.

----

[1] Where `/feature-flags` is your custom path prefix, in this case taken from the readme.

**Comment by tompave** [comment]
Actually, to save time, here is a PR: https://github.com/tompave/fun_with_flags_ui/pull/11

You can also try that branch to check if it solves the problem.

**Comment by egze** [comment]
Thanks for the ideas and the PR. We sadly can't change the loadbalancer rules, and the solution to intercept the requests, while might work - is really just a workaround.

What we are doing in the mean time - is manually extracting the file in our deployment pipeline. But this is also a hacky workaound, I think.

Anyway, thanks for the PR again. Please merge.

**Comment by tompave** [comment]
Ok, released as `0.7.2`.
https://hex.pm/packages/fun_with_flags_ui/0.7.2
