### ISSUE TITLE
Persistent XSS Vulnerability 

### ISSUE THREAD

**Issue by thelightcosine** [tompave/fun_with_flags_ui#28]
The FunWithflagsUI is vulnerable to persistent XSS attacks. 

For Example a request in our Application like this:
```
POST /feature-flags/flags/some_flag/actors HTTP/1.1
_csrf_token=ZCoOGggmewMSFTxcFVkFMBU3PDITDC4n4ngbON8wMAeqYaDB-rVgwNXr&actor_id=aa<h1>bb&enabled=true
```

Results in page with the following HTML:
```html
                <li class="list-group-item px-0">
                  <div id="actor_aa<h1>bb" class="container fwf-I-hate-grids">
  <div class="row no-gutters">
    <div class="col-lg-8 col-md-7 col-sm-5 col-3 text-left">
      <code>aa<h1>bb</code>
    </div>
```

Similarly GET paramaters can also generate XSS within the page:
```
GET /feature-flags/flags/some_other_flag#actor_cat:%3Ch1%3EXSSHERE HTTP/1.1
```

will get
```html
<h1><code>XSSHERE</code>
    </h1>
```
    
All user inputs must be properly sanitised and encoded . See https://owasp.org/www-community/attacks/xss/ for more details about XSS

**Comment by tompave** [comment]
Apologies for the long wait.

I think that if we can better sanitize user input and add XSS protextion we should. That being said, all pages and HTTP endpoints provided by this package [should be behind authentication](https://github.com/tompave/fun_with_flags_ui#security). If a malicious user is able to send requests to any of these endpoints, then XSS would be the last of your concerns because there is a more urgent and more dangerous breach.
