### ISSUE TITLE
Problem to load gzipped bootstrap in production

### ISSUE THREAD

**Issue by hugomaiavieira** [tompave/fun_with_flags_ui#8]
Hi,

In production, I'm not able to load the bootstrap gzipped file and Google Chrome is giving me this error message:

```
Refused to apply style from 'https://www.example.com/admin/feature-flags/assets/bootstrap.min.css'
because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking
is enabled.
```

![fwf](https://user-images.githubusercontent.com/73012/51272481-55bf0a80-19b1-11e9-849f-1a9fe7bea416.png)

The `style.css` is working correctly, but the gzipped bootstrap don't. I couldn't find any Nginx config that was blocking it somehow. I guess I would have to add `gzip_static on;` for this location (didn't test though).

Wouldn't be better to load the file from bootstrap CDN instead? Like:

```html
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
```

I appreciate any help :)

**Comment by tompave** [comment]
Hi, and thanks for using the package!

It should work because [the router includes]https://github.com/tompave/fun_with_flags_ui/blob/v0.7.0/lib/fun_with_flags/ui/router.ex#L18-L21):

```elixir
  plug Plug.Static,
    gzip: true,
    at: "/assets",
    from: :fun_with_flags_ui
```

But yes, if somehow nginx is intercepting the request and trying to serve the file before the Plug router, it could cause problems without [`gzip_static`](https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html#gzip_static).

A few questions:

1. Are you running an Erlang release?
2. Can you see the request for the css file in the nginx log?
3. Can you try to enable `gzip_static`?

**Comment by tompave** [comment]
> Wouldn't be better to load the file from bootstrap CDN instead?

Yes, although I like the idea of having it self-contained.
I guess it could be supported with a config option.

**Comment by hugomaiavieira** [comment]
Hi @tompave! Thanks for your work in the package!

Answering your questions:

1. I'm running a Phoenix app with a distillery release.
2. Yep, it gives me a 404. But if I access the route with the ".gz" I can download the file. So, probably if I enable `gzip_static` it will work.
3. Right now the `gzip_static` are enabled for specific `location`s. I will try to enable it as well, but I will have to do some work, generate a new AMI and etc. That's one reason I would like to avoid it. Would be nice to not have to change ifrastructure stuff because of a not so complex dependency.

Maybe would be even better to not have bootstrap as dependency at all, with a very tiny css.

**Comment by tompave** [comment]
> But if I access the route with the ".gz", I can download the file. So, probably if I enable gzip_static, it will work.
> Right now the gzip_static are enabled for specific locations. I will try to enable it as well, but I will have to do some work, generate a new AMI, etc.

I would try that first.

> That's one reason I would like to avoid it. Would be nice not to have to change infrastructure stuff because of a not so complex dependency.

I hear you, but then I could reply that reverse proxy rules targeting front end assets are an application concern. If modifying them requires to "change infrastructure stuff", it sounds more like an infrastructure management problem.

> Maybe would be even better to not have bootstrap as a dependency at all, with a little CSS (I'm not a specialist, but I can open a PR if you think it is a good idea).

I'm afraid I disagree, sorry. Including "a little CSS" that I or a contributor has manually written is no different from vendoring/bundling some open source CSS from a library. The problem here is that the library defaults to serve gzipped assets, and your nginx set up is stepping in and throwing an error before the library can do its job (at least, this is our working theory at the moment). I understand that it's frustrating that it's not "just working", but I don't think that replacing the CSS with other CSS is the right move.

**Comment by hugomaiavieira** [comment]
Yep, indeed. I agree with you on both points :+1: 

I will close the issue since it is not a package problem and enabling `gzip_static` will probably fix it for me.

Thanks!

**Comment by tompave** [comment]
Ok @hugomaiavieira 👍 
Please let me know if it fixes it or it doesn't. If you get to the root cause, it would be good to add it to the readme.
